/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import project.Language;
import java.util.Date;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author hp
 */
public class Kiswahili extends javax.swing.JFrame {
int account;
    /**
     * Creates new form Kiswahili
     */
    public Kiswahili() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        weka = new javax.swing.JButton();
        kutoa = new javax.swing.JButton();
        baki = new javax.swing.JButton();
        histolia = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kiwango = new javax.swing.JTextField();
        futa = new javax.swing.JButton();
        dhibitishaKuweka = new javax.swing.JButton();
        dhibitishaKutoa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        skrini = new javax.swing.JTextArea();
        nyuma = new javax.swing.JButton();
        toka = new javax.swing.JButton();
        chapa = new javax.swing.JButton();
        upya = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1350, 700));
        setPreferredSize(new java.awt.Dimension(1350, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("KARIBU SMARTCASH ATM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("BONYEZA CHAGUO LAKO HAPO CHINI");

        weka.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        weka.setText("WEKA");
        weka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wekaActionPerformed(evt);
            }
        });

        kutoa.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        kutoa.setText("KUTOA");
        kutoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kutoaActionPerformed(evt);
            }
        });

        baki.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        baki.setText("BAKI");
        baki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiActionPerformed(evt);
            }
        });

        histolia.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        histolia.setText("HISTORIA");
        histolia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                histoliaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("KIWANGO");

        kiwango.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kiwango.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        futa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        futa.setText("FUTA");
        futa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futaActionPerformed(evt);
            }
        });

        dhibitishaKuweka.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dhibitishaKuweka.setText("DHIBITISHA KUWEKA");
        dhibitishaKuweka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhibitishaKuwekaActionPerformed(evt);
            }
        });

        dhibitishaKutoa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dhibitishaKutoa.setText("DHIBITISHA KUTOA");
        dhibitishaKutoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dhibitishaKutoaActionPerformed(evt);
            }
        });

        skrini.setColumns(20);
        skrini.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        skrini.setRows(5);
        skrini.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jScrollPane1.setViewportView(skrini);

        nyuma.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nyuma.setText("<-NYUMA");
        nyuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyumaActionPerformed(evt);
            }
        });

        toka.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        toka.setText("TOKA");
        toka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokaActionPerformed(evt);
            }
        });

        chapa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chapa.setText("PIGA CHAPA");
        chapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chapaActionPerformed(evt);
            }
        });

        upya.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        upya.setText("UPYA");
        upya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(366, 366, 366)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(weka, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kutoa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(upya)
                                        .addGap(172, 172, 172)
                                        .addComponent(chapa)
                                        .addGap(284, 284, 284))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(baki, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(histolia, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(futa)
                                        .addGap(182, 182, 182))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(dhibitishaKuweka)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(dhibitishaKutoa))
                                            .addComponent(kiwango, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(150, 150, 150)
                                        .addComponent(nyuma)
                                        .addGap(127, 127, 127)
                                        .addComponent(toka)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(412, 412, 412)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baki)
                    .addComponent(histolia)
                    .addComponent(kutoa)
                    .addComponent(weka))
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kiwango, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(futa)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dhibitishaKuweka)
                                    .addComponent(dhibitishaKutoa)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nyuma)
                                    .addComponent(toka))))
                        .addGap(332, 332, 332))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(upya)
                            .addComponent(chapa))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void wekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wekaActionPerformed
        kiwango.setEnabled(true);
        skrini.setEnabled(false);
        kutoa.setEnabled(false);
        baki.setEnabled(false);
        histolia.setEnabled(false);
        futa.setEnabled(true);
        dhibitishaKuweka.setEnabled(true);
        dhibitishaKutoa.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_wekaActionPerformed

    private void kutoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kutoaActionPerformed
        kiwango.setEnabled(true);
        skrini.setEnabled(false);
        weka.setEnabled(false);
        baki.setEnabled(false);
        histolia.setEnabled(false);
        futa.setEnabled(true);
        dhibitishaKutoa.setEnabled(true);
        dhibitishaKuweka.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_kutoaActionPerformed

    private void bakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiActionPerformed
        skrini.setText("************************************************************\n");
        skrini.setText(skrini.getText()+"  \t          $   SMARTCASH ATM   $\n");
        skrini.setText(skrini.getText()+"************************************************************\n");
        Date obj = new Date();
        String date = obj.toString();

        skrini.setText(skrini.getText()+"\n   "+date+"\n");
        skrini.setText(skrini.getText()+"\n  Baki lako : "+getCurrentBalance(PinAtm1.account)+"\n\n");
        skrini.setText(skrini.getText()+" \n   Akaunti: "+PinAtm1.account+"\n");
        skrini.setText(skrini.getText()+"\t\t Mhuri \n ");
        kiwango.setEnabled(false);
        skrini.setEnabled(true);
        futa.setEnabled(false);
        dhibitishaKuweka.setEnabled(false);
        dhibitishaKutoa.setEnabled(false);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        weka.setEnabled(false);
        baki.setEnabled(false);
        histolia.setEnabled(false);
        kutoa.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_bakiActionPerformed

    private void histoliaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_histoliaActionPerformed
        skrini.setText("*******************************************************\n");
        skrini.setText(skrini.getText()+"  \t $   SMARTCASH ATM   $\n");
        skrini.setText(skrini.getText()+"*******************************************************\n");
        Date obj = new Date();
        String date = obj.toString();

        skrini.setText(skrini.getText()+"\n"+date+"\n");
        skrini.setText(skrini.getText()+"Umefanya yafutayo: \n");
        skrini.setEnabled(true);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        dhibitishaKuweka.setEnabled(false);
        dhibitishaKutoa.setEnabled(false);
        kiwango.setEnabled(false);
        futa.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_histoliaActionPerformed

    private void futaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futaActionPerformed
        kiwango.setText(null);
        kutoa.setEnabled(true);
        baki.setEnabled(true);
        histolia.setEnabled(true);
        weka.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_futaActionPerformed

    private void dhibitishaKuwekaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhibitishaKuwekaActionPerformed
        int amountDeposit = Integer.parseInt(kiwango.getText());
        //       System.out.println(amountDeposit);
        int x = getCurrentBalance(PinAtm1.account);
        //       System.out.println(x);
        int y;
        y = x + amountDeposit;
        //       System.out.println(y);
        updateBalance( y, PinAtm1.account);
        if(amountDeposit <= 0){
            JOptionPane.showMessageDialog(null, "HAURUHUSIWI! ","onyo", JOptionPane.ERROR_MESSAGE);
        }

        //       JOptionPane.showMessageDialog(null, "Update successful");
        else{
        skrini.setText("************************************************************\n");
        skrini.setText(skrini.getText()+"  \t          $  SMARTCASH ATM   $\n");
        skrini.setText(skrini.getText()+"************************************************************\n");
        Date obj = new Date();
        String date = obj.toString();

        skrini.setText(skrini.getText()+"\n   "+date+"\n");
        skrini.setText(skrini.getText()+" \n   Umeweka shilingi "+amountDeposit+" kwa akaunti yako"+"\n");
        skrini.setText(skrini.getText()+" \n   Akaunti: "+PinAtm1.account+"\n");
        skrini.setText(skrini.getText()+" \n   Kuangalia baki bonyeza BAKI \n");
        skrini.setText(skrini.getText()+"\t\t Mhuri");

        kiwango.setEnabled(false);
        skrini.setEnabled(true);
        kutoa.setEnabled(true);
        baki.setEnabled(true);
        histolia.setEnabled(true);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        weka.setEnabled(true);
        futa.setEnabled(false);
        // TODO add your handling code here:
        }
    }//GEN-LAST:event_dhibitishaKuwekaActionPerformed

    private void dhibitishaKutoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dhibitishaKutoaActionPerformed

        kiwango.setEnabled(false);
        skrini.setEnabled(true);
        kutoa.setEnabled(true);
        baki.setEnabled(true);
        histolia.setEnabled(true);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        weka.setEnabled(true);
        futa.setEnabled(false);

        int amountWithdraw = Integer.parseInt(kiwango.getText());
        //       System.out.println(amountDeposit);
        int x = getCurrentBalance(PinAtm1.account);
        //       System.out.println(x);
        int z;
        z = x - amountWithdraw;
        //       System.out.println(y);
        updateBalance( z, PinAtm1.account);
        if(amountWithdraw <= 0){
            JOptionPane.showMessageDialog(null, "HAURUHUSIWI! ","Onyo", JOptionPane.ERROR_MESSAGE);
        }
        if(amountWithdraw > x){
            JOptionPane.showMessageDialog(null, "Kiwango unachotoa ni zaidi ya baki lako Unachukua Deni?","Onyo",JOptionPane.ERROR_MESSAGE );
//           
          
       }
        else{
        skrini.setText("************************************************************\n");
        skrini.setText(skrini.getText()+"  \t        $   SMARTCASH ATM   $\n");
        skrini.setText(skrini.getText()+"************************************************************\n");
        Date obj = new Date();
        String date = obj.toString();

        skrini.setText(skrini.getText()+"\n   "+date+"\n");
        skrini.setText(skrini.getText()+" \n   Umetoa shilingi: "+amountWithdraw+" kutoka kwa akaunti yako"+"\n");
        skrini.setText(skrini.getText()+" \n   Akaunti: "+PinAtm1.account+"\n");
        skrini.setText(skrini.getText()+" \n   Kuangalia baki bonyeza BAKI \n");
        skrini.setText(skrini.getText()+"\t\t Mhuri");
        // TODO add your handling code here:
        }
    }//GEN-LAST:event_dhibitishaKutoaActionPerformed

    private void tokaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokaActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_tokaActionPerformed

    private void chapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chapaActionPerformed
        try
        {
            skrini.print();
        }
        catch(Exception ex)
        {

        }

        kiwango.setEnabled(true);
        skrini.setEnabled(true);
        futa.setEnabled(true);
        dhibitishaKuweka.setEnabled(true);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        weka.setEnabled(true);
        baki.setEnabled(true);
        histolia.setEnabled(true);
        kutoa.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_chapaActionPerformed

    private void upyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upyaActionPerformed
        kiwango.setText(null);
        skrini.setText(null);
        kiwango.setEnabled(true);
        skrini.setEnabled(true);
        futa.setEnabled(true);
        dhibitishaKuweka.setEnabled(true);
        chapa.setEnabled(true);
        upya.setEnabled(true);
        weka.setEnabled(true);
        baki.setEnabled(true);
        histolia.setEnabled(true);
        kutoa.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_upyaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        kiwango.setEnabled(false);
        skrini.setEnabled(false);
        futa.setEnabled(false);
        dhibitishaKuweka.setEnabled(false);
        dhibitishaKuweka.setEnabled(false);
        chapa.setEnabled(false);
        upya.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void nyumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyumaActionPerformed
        Language Kiswahili = new Language();
        Kiswahili.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_nyumaActionPerformed
    
    public void updateBalance(int newBalance, int acc){
       
        Connection con = PinAtm1.con;               
        try {           
            
            PreparedStatement ps;
            ps = con.prepareStatement("UPDATE users SET balance = ? WHERE accountNo = ?");
            ps.setInt(1, newBalance);
            ps.setInt(2, acc);
            
          ps.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(PinAtm1.class.getName()).log(Level.SEVERE, null, ex);

        }
        
        
    }
    public int getCurrentBalance(int acc){
        try {
            PinAtm1 atm = new PinAtm1();
            Connection con = atm.getConnection();
            
            PreparedStatement ps;
            ps = con.prepareStatement("SELECT * FROM users WHERE accountNo = ? ");
            ps.setInt(1, acc);
            
//            System.out.println("Hellow world");
            ResultSet result = ps.executeQuery();
            if(result.next()){
                return result.getInt("balance");
            }
            return 0;
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(English.class.getName()).log(Level.SEVERE, null, ex);
            return 0;
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kiswahili.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kiswahili.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kiswahili.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kiswahili.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kiswahili().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baki;
    private javax.swing.JButton chapa;
    private javax.swing.JButton dhibitishaKutoa;
    private javax.swing.JButton dhibitishaKuweka;
    private javax.swing.JButton futa;
    private javax.swing.JButton histolia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kiwango;
    private javax.swing.JButton kutoa;
    private javax.swing.JButton nyuma;
    private javax.swing.JTextArea skrini;
    private javax.swing.JButton toka;
    private javax.swing.JButton upya;
    private javax.swing.JButton weka;
    // End of variables declaration//GEN-END:variables
}
